# Generated by Django 2.2.7 on 2020-03-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性别'),
        ),
    ]
