# Generated by Django 2.2.7 on 2020-03-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='新用户', max_length=20, verbose_name='昵称'),
        ),
    ]
