# Generated by Django 2.2.7 on 2020-03-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200307_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='author',
            new_name='user',
        ),
    ]
