# Generated by Django 2.2.7 on 2020-03-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blogs.Tag', verbose_name='文章标签'),
        ),
    ]
