# Generated by Django 2.2.19 on 2021-03-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200330_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章内容', 'verbose_name_plural': '文章内容'},
        ),
        migrations.CreateModel(
            name='ArticlePlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_view', models.BigIntegerField(default=0, verbose_name='浏览量')),
                ('thumb', models.BigIntegerField(default=0, verbose_name='点赞量')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.Article', verbose_name='文章内容')),
            ],
            options={
                'verbose_name': '文章附加信息',
                'verbose_name_plural': '文章附加信息',
            },
        ),
    ]
